### PR TITLE
add workshop to github pages

### PR DESCRIPTION
**Pull request by stevemart**
This PR is a gigantic port of the wonderful work that @boxcarton @tmarkiewicz @samuelcouch and @yrezgui did in this repo: https://github.com/watson-developer-cloud/watson-vision-coreml-code-pattern

In an effort to consolidate our CoreML assets I am proposing that we merge the content from the aforementioned repo and include it as a github pages branch for this repo. This repo is generally more publicly known, has over 400 stars, is the basis of the code pattern, and will be the basis of the starter kit.

@devinaconley please review. I have built this locally by running `bundle install` and `bundle exec jekyll serve`, below is a snapshot.

screen shot 2018-09-10 at 3 25 26 pm

### CODE REVIEW

**Comment by yrezgui** [comment]
I ran the workshop three weeks ago in a hotel in Denver and we were surprised to see that cloning this repository would fetch ~500 MB. It will be good to clean the repository before merging everything, making it harder for attendees to download it.

**Comment by stevemart** [comment]
yeah... that's an ouch.

```
 28M	./_advanced-original
 28M	./_advanced-original/assets
 28M	./_lessons
 28M	./_lessons/assets
 31M	./_advanced-console
 31M	./_advanced-console/assets
 32M	./_advanced
 32M	./_advanced/assets
 32M	./_site/advanced
 32M	./_site/advanced/assets
 34M	./_simple
 34M	./_simple/assets
 34M	./_simple_console
 34M	./_simple_console/assets
 34M	./_site/simple
 34M	./_site/simple/assets
 44M	./_arduino
 44M	./_arduino/assets
 44M	./_multiple
 44M	./_multiple/assets
```

**Comment by devinaconley** [comment]
The `.git` history for this repo is also almost 200mb...
```
416K    ./Core ML Vision Custom/Core ML Vision Custom
 24K    ./Core ML Vision Custom/Core ML Vision Custom.xcodeproj
448K    ./Core ML Vision Custom
8.0K    ./QuickstartWorkspace.xcworkspace/xcshareddata
 12K    ./QuickstartWorkspace.xcworkspace
193M    ./.git/objects
4.0K    ./.git/info
 12K    ./.git/logs
 44K    ./.git/hooks
8.0K    ./.git/refs
193M    ./.git
 20K    ./Core ML Vision Simple/Core ML Vision Simple.xcodeproj
 44K    ./Core ML Vision Simple/Core ML Vision Simple
 31M    ./Core ML Vision Simple
3.5M    ./Training Images
228M    .
```

**Comment by stevemart** [comment]
OK. This is ready for review again. Apparently static files cannot be placed in directories that begins with `_`.

**Comment by stevemart** [comment]
Pretty sure we can get the images down to ~30MB without any major quality loss: ...

```
smartinelli-mac images $ mogrify -path . -resize 1920x1920 -quality 70 *.png
smartinelli-mac images $ mogrify -path . -resize 1920x1920 -quality 70 *.jpg
smartinelli-mac images $ mogrify -path . -resize 1920x1920 -quality 70 *.jpeg
smartinelli-mac images $ du -h | sort -h
 33M	.
```

**Comment by bourdakos1** [comment]
@stevemart this is a pull request into the `gh-pages` branch, correct? If so, I’m not too worried about the size of it. I’m more concerned with the current size of the git history for the `master` branch.

**Comment by devinaconley** [comment]
@bourdakos1 @stevemart - okay with merging this into `gh-pages`?

separate issue tracked here for size of git history:
https://github.com/watson-developer-cloud/visual-recognition-coreml/issues/37

**Comment by stevemart** [comment]
@devinaconley i don't believe we need this PR (or the original repo (https://github.com/watson-developer-cloud/watson-vision-coreml-code-pattern) ) any longer. 

@samuelcouch has published the workshop at https://developer.ibm.com/tutorials/watson-visual-recognition-with-core-ml-single-model/ which i believe suites the needs of the advocacy team. We can close this PR.

@samuelcouch @yrezgui @boxcarton please confirm before I close this PR.

**Comment by tmarkiewicz** [comment]
@stevemart the workshop that @samuelcouch published is only one of the four that are included in this repo

**Comment by stevemart** [comment]
@tmarkiewicz hi there, finally looping back to this.

I looked at the four tutorials in https://github.com/watson-developer-cloud/watson-vision-coreml-code-pattern and there are a handful of lines that are different between them. Training a single model vs multiple, or using your own pictures vs the ones provided. 

I don't think that justifies the need for 3 new assets entirely. I'd rather expand https://developer.ibm.com/tutorials/watson-visual-recognition-with-core-ml-single-model/ with different NOTES or optional steps that a reader to perform or skip over, instead.

I'm going to close this PR for now.

**Pull request closed without merging**
